### ISSUE TITLE
Uploading empty folder through FileZilla creates "null" file in the folder

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#115]
I am calling this "null" file as it has no name or size and doesn't download through "download" button. It does however download through "COPY LINK".  When downloaded the file is named "download" and has zero size, as seen under Windows.

Observed in tester and dev mode.

![image](https://user-images.githubusercontent.com/15882196/108087655-a8da7e80-709d-11eb-8fd2-f8f615755f41.png)

**Comment by super3** [comment]
May be related to #92

**Comment by nerdatwork** [comment]
My console showed this.

![image](https://user-images.githubusercontent.com/15882196/108089800-01ab1680-70a0-11eb-8e78-7f13cde6d3c7.png)
