### ISSUE TITLE
"Introvert" column headers

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#131]
https://user-images.githubusercontent.com/15882196/108382296-ace9d600-722e-11eb-9764-b0480ce51367.mp4

A picture is worth thousand words that's why I have a video 🤓

**Comment by super3** [comment]
Oh nice catch. Looks like that happens only when you have no files in the bucket.

**Comment by Kalloritis** [comment]
Additionally, this happens while you have no existing files and 1 file that you are actively uploading.

**Comment by super3** [comment]
Will be fixed on the next version of vortex.
