### ISSUE TITLE
Freeze Duplicati documentation bookmarks at top of page when scrolling down

### ISSUE THREAD

**Issue by Kalloritis** [storj-thirdparty/vortex#147]
When scrolling down on the documentation page for the duplicati implementation, I believe the bookmarks on the left hand should freeze at the top of the browser viewport when scrolling down so that they're always visible to jump to the different sections.

It also could change the blue highlight depending on which section is scrolled to so that you know which part your in respective to the other steps overview.

**Comment by super3** [comment]
@Kalloritis Thanks for the issue. We are going to be redesigning, so I'm going to close it. This may not be an issue in the new version.
