### ISSUE TITLE
[Feature Request] Ability to select multiple files or folders for deletion

### ISSUE THREAD

**Issue by acbcarneiro** [storj-thirdparty/vortex#161]
Using the Web UI it is currently impossible to delete more than one file at a time.
After a run with Duplicati, I have hundreds of pieces and it's not possible to delete them all in one go.

**Comment by gabedealmeida** [comment]
@acbcarneiro This feature has now been added to our application. Please let us know what you think about it if you have the chance 😃

**Comment by acbcarneiro** [comment]
Hi, Gabe
It could be because I have too many files, but if I select them all and click them for deletion I get huge amount of browser memory usage and the operation seems to timeout without file deletion.
