### ISSUE TITLE
When uploading files on the Web Interface, changing tabs cancels uploads even if you click "cancel" on the error message

### ISSUE THREAD

**Issue by acbcarneiro** [storj-thirdparty/vortex#177]
When performing file operations in the Web UI, clicking into a different tab brings up an error message saying that the file upload will be cancelled.
Clicking "cancel" still moves you away form the files tab and cancels the operation.

Incidentally, when deleting multiple files you get the same error message (saying that file uploads will be cancelled), even though there are actually no file upload operations happening. The error message is not contextual.

**Comment by super3** [comment]
@acbcarneiro We made significant changes to this page since you made this issue. Can you see if we fixed it?

**Comment by super3** [comment]
@gabedealmeida As far as I can tell this is unreachable code and should be deleted: https://github.com/storj-thirdparty/vortex/blob/main/ui/src/components/FileBrowser.vue#L604

**Comment by super3** [comment]
This should be fixed
