### ISSUE TITLE
Browser Tab Not Selected

### ISSUE THREAD

**Issue by super3** [storj-thirdparty/vortex#178]
With recent updates the file browser tab is not selected even when viewing the file browser:

![browser](https://user-images.githubusercontent.com/60975/109400968-ce774b80-7919-11eb-8db2-96b7976bb16a.png)

**Comment by super3** [comment]
@gabedealmeida Not sure that fixed it

**Comment by gabedealmeida** [comment]
@super3 It's working on my end. Is it not selecting the browser tab at all for you?
