### ISSUE TITLE
Removing placeholder .vortex_placeholder removes folder

### ISSUE THREAD

**Issue by veeroo** [storj-thirdparty/vortex#18]
I get what's the point of this placeholder for empty directories, but It may ruin folders structure in case someone delete this file by accidentally. Maybe it is possible to make this file invisible or filtered on frontend? Or display some warning when deleting

**Comment by nerdatwork** [comment]
I would like to add its more like **deleting all files inside a folder deletes the folder**. Newly created folder has this `.vortex` file so it has the same effect.

**Comment by montyanderson** [comment]
@veeroo @nerdatwork Storj/Tardigrade is object storage so has no concept of folders, only prefixes (`/prefix/my-file.txt`). We create a `.vortex-placeholder` file so that the folder you create can be found as a prefix for an existing file.

Do you think we should hide this file from the user?

**Comment by nerdatwork** [comment]
Yes hiding it would make more sense.

**Comment by super3** [comment]
Fixed
