### ISSUE TITLE
Trash can icon inside folder does nothing

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#180]
![image](https://user-images.githubusercontent.com/15882196/109445595-ee1b8a80-7a65-11eb-9960-eff2f980f7d4.png)

A tooltip might help when it starts working.
Is it to delete entire folder ? 
Is it to select multiple files < entire folder for deletion?

**Comment by gabedealmeida** [comment]
The issue of the trash icon not doing its job of deleting the selected files and folders was solved with this PR https://github.com/storj-thirdparty/vortex/issues/194 :)
