### ISSUE TITLE
Cannot download shared file using generated link

### ISSUE THREAD

**Issue by veeroo** [storj-thirdparty/vortex#20]
I've clicked Share, got share link, pasted in incognito mode but got XML file like this in result:
`<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>Lexmark_Universal_v2_UD1_Installation_Package_02212020.exe</Key>
<BucketName>delta2-23</BucketName>
<Resource>/delta2-23/Lexmark_Universal_v2_UD1_Installation_Package_02212020.exe</Resource>
<RequestId>165A26B0A016CDC9</RequestId>
<HostId>75f8de52-b63d-4b08-8a84-513f4e45bb75</HostId>
</Error>`

**Comment by super3** [comment]
@veeroo Are you able to replicate this bug. We may have fixed it.

**Comment by super3** [comment]
Believe we fixed this issue.
