### ISSUE TITLE
Loading spinner when navigating to `app/browser` and clicking on a folder

### ISSUE THREAD

**Issue by gabedealmeida** [storj-thirdparty/vortex#204]
Whenever one navigates to `app/browser` there should be a loading spinner so that the user knows we're fetching their files for them. The same when they click on a folder. As opposed to the user just sitting there not knowing what is going on.

**Comment by super3** [comment]
I think perhaps we should do a lazy load instead.

**Comment by gabedealmeida** [comment]
@super3 Once the CORS issue has been resolved, let me know what you think about this implementation. Can totally scratch it and do anything else :)
