### ISSUE TITLE
Clicking on `..` more than the current folder nesting level leads to a blank page

### ISSUE THREAD

**Issue by gabedealmeida** [storj-thirdparty/vortex#219]
Clicking on `..` to go back more times than the number of nested folders that you've navigated into leads to a state with only the dashboard tabs showing.

![Screen Shot 2021-03-05 at 3 23 25 PM](https://user-images.githubusercontent.com/52146328/110169478-bd6d8500-7dc6-11eb-9691-a6be72b22a27.png)

![Screen Shot 2021-03-05 at 3 26 11 PM](https://user-images.githubusercontent.com/52146328/110169744-1fc68580-7dc7-11eb-9b0f-f50b596c7144.png)

**Comment by super3** [comment]
Moved to https://github.com/storj/browser/issues/20
