### ISSUE TITLE
Trash can icon shows up by default inside empty folder

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#220]
Ideally it should show up when any file is selected.

![image](https://user-images.githubusercontent.com/15882196/110208037-cd5f9480-7eac-11eb-86d8-db0b5553ef20.png)

**Comment by gabedealmeida** [comment]
@nerdatwork @super3 This problem was fixed by all the merges we did this morning :)

**Comment by nerdatwork** [comment]
I can confirm now that this issue is resolved. Thank you @gabedealmeida
