### ISSUE TITLE
Inability to select multiple files using CTRL key

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#221]
Continuous files can be selected by using SHIFT key but non-continuous/alternate files can't be selected.

**Comment by gabedealmeida** [comment]
@super3 I made a PR for this issue on the Browser repo https://github.com/storj/browser/pull/3. Browsers do not emit an event for CTRL + click but they do emit an event for command + click (for Macs), and the windows alternative which I believe is Windows + click. I added support for CTRL + click should that become available or be supported on the Windows side of things. I also added more functionality to emulate more closely what the current file browser standards for mass selection do and allow :)
