### ISSUE TITLE
[Chrome] A folder is inaccessible if folder name is empty

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#24]
![image](https://user-images.githubusercontent.com/15882196/104621853-8fb56b00-56b6-11eb-8aea-f097da8255b0.png)

Created a folder without name under a folder that had a name "bigfiles". This folder is inaccessible under Chrome browser.

**Comment by montyanderson** [comment]
Fixed!

**Comment by nerdatwork** [comment]
~I could still create inaccessible (folder) prefix. What was the fix ?~

Edit: Fixed
