### ISSUE TITLE
[Feature Request] Rename, Share and Properties buttons for folders

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#26]
Folders should have these buttons. Additionally if "Properties" button is given it should appropriate items

- Number of files
- Size of Folder
- Size in MB / MiB
- Creation Date

**Comment by super3** [comment]
Related to #25. 

@nerdatwork These are at least 2 separate issues. Can you please split?

**Comment by super3** [comment]
You can now delete folders.

**Comment by super3** [comment]
Moved to https://github.com/storj/browser/issues/55
