### ISSUE TITLE
Share Link URL is tooo long.

### ISSUE THREAD

**Issue by willtopping** [storj-thirdparty/vortex#27]
Example:

https://gateway.tardigradeshare.io/delta2-20/puppy.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=jupe7g7nbswcusxpfl6rysg75y2a%2F20210114%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210114T165647Z&X-Amz-Expires=86400&X-Amz-Signature=d585262d2cb6449520bac86fdd9180e46afc44b5d97e43e456c05ac34fae89e2&X-Amz-SignedHeaders=host

**Comment by super3** [comment]
@willtopping I agree. We will research how to do this properly.

**Comment by super3** [comment]
@calebcase @jtolio How could securely turn this into a short link (with as little state as possible)?

**Comment by jtolio** [comment]
we don't have a way of applying a macaroon transformation to an access *key* sadly. if you had the access grant this is trivial, but if you only have the access key we're going to need to noodle on what we even want to do here. as it stands, the long url + signature is protecting unauthorized users from accessing data they shouldn't. if you were to switch to the non-aws-style linksharing (link.tardigradeshare.io), that would be shorter, but it currently requires access grants for correct restriction.

**Comment by willtopping** [comment]
What about applying some post processing shortening service automatically?

**Comment by super3** [comment]
Moved to https://github.com/storj/browser/issues/64
