### ISSUE TITLE
Password restrictions

### ISSUE THREAD

**Issue by littleskunk** [storj-thirdparty/vortex#273]
*Expected Behavior*
I want to use a generate password like this: `pjÉ3lLÄ&Âîe=;ç9CÂxÓÔí{®®Ä4_84ã&k[÷ã7MíhYçëß¤ç½L081`
For extra security I sometimes even generate a longer password. I expect the side to just accept any password I throw at it. The side should not complain about a password that contains invalid characters or is too long.

*Actual Behavior*
My password is too long and I don't get any feedback how short it needs to be. I wouldn't be supprised if there are other password restrictions in place that I would trigger one by one. I will try it exactly 3 times. If I didn't find out what the password rules are within these 3 attempts I will just give up. I am not willing to accept a less optimal password strength. I want the maximum allowed password strength.

**Comment by super3** [comment]
@littleskunk For the next version we will just be using the the satellite login, so there will not be separate login system.
