### ISSUE TITLE
[Feature request] [UI/UX] Use History API to make navigation into specific folders easier

### ISSUE THREAD

**Issue by veeroo** [storj-thirdparty/vortex#28]
It would be nice to be able to jump into particular folder with with link. I know tardigrade way of storing files and the fact that folders are "virtual" but if we have directories in web interface, I believe it would be better to update url when jumping between folders. For instance, I'd like to add some bookmarks in my browser for particular directories - now it cannot be done

**Comment by super3** [comment]
Related to #49
