### ISSUE TITLE
Issue 179 still persists

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#288]
#179 

![image](https://user-images.githubusercontent.com/15882196/111333996-314a4000-8699-11eb-8b5a-e7a5b8ee317e.png)

Uploading a file `test.png` in this `nonexistantfolder` will upload the file to root and prefix the folder name to the file. New uploaded file will have the file name `nonexistantfoldertest.png`

**Comment by super3** [comment]
This is ok.
