### ISSUE TITLE
Never ending spinner during folder creation

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#304]
Spinner is visible while creating new folder if invalid characters like `.` , `..`, `/` are entered then ENTER key is pressed.

![image](https://user-images.githubusercontent.com/15882196/112024002-c5b11880-8b59-11eb-8b21-7239924ce0f0.png)

**Comment by super3** [comment]
@nerdatwork This issue has been moved to the file browser component: https://github.com/storj/browser/issues/48
