### ISSUE TITLE
[Feature Request] Ability to Share via Social media buttons

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#31]
![image](https://user-images.githubusercontent.com/15882196/104623188-1fa7e480-56b8-11eb-98ea-ceccfd045e9d.png)

Sharing link directly on my Twitter/Facebook/Instagram feed. Similar to how "Post it on twitter" works.

**Comment by super3** [comment]
If we do this we should probably implement #25 first.

**Comment by super3** [comment]
Won't be implementing this. :-(
