### ISSUE TITLE
[Feature Request] Delete confirmation for all delete functions

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#34]
It's very much possible to click the delete button by mistake. There must be a delete confirmation for all "Delete" functionality. 

A notification should also be shown after successful deletion.

**Comment by super3** [comment]
@gabedealmeida Make this inline, no popups.

**Comment by super3** [comment]
@nerdatwork Although we are not going to add a notification, we now have delete confirmation.
