### ISSUE TITLE
[Feature Request] Duplicate folder name should give error

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#36]
A second folder with same name does not give any error. It should either prompt user to change name or automatically add `(1)` to it the way Windows does.
Example: 
FolderOne
FolderOne(1)

**Comment by montyanderson** [comment]
The 'Save Folder' button is now disabled when one with the new name already exists.

**Comment by nerdatwork** [comment]
The `Save Folder` button is disabled by default and now empty prefix (folder) can't be created. But same folder name is accepted and no notification is given.

![image](https://user-images.githubusercontent.com/15882196/106035997-c057c480-60fa-11eb-87f2-6d80e6331601.png)

Edit: Fixed! <3
