### ISSUE TITLE
[Feature Request] Search functionality

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#38]
Ability to search for a file based on filename or extension

**Comment by super3** [comment]
@nerdatwork This might be difficult to do when we add client side encryption.

**Comment by nerdatwork** [comment]
Oh okay. It works in Filezilla as of now but would it still work after enabling client side encryption.

**Comment by super3** [comment]
We won't be able to support this feature any time soon. Although it would be nice to have. Users will expect search functionality that will look in the files and folders, but for security and privacy purposes we are not easily able to do it.

**Comment by super3** [comment]
I'm going to leave this open for now as aspirational.

**Comment by super3** [comment]
Will not be able to do this in this repo.
