### ISSUE TITLE
[Feature Request] Additional info for total files, storage & Bandwidth

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#39]
![image](https://user-images.githubusercontent.com/15882196/104633330-fccffd00-56c4-11eb-809c-3720f6369fda.png)

Instead of letting customer calculate how many more files can be added it can be shown as above ^

This can be implemented for all other metrics like Storage / Bandwdith

**Comment by super3** [comment]
I think what we have now is sufficient. Users should really just need to know if they are getting close to the plan limits.

**Comment by super3** [comment]
If additional users report this issue that we can reconsider.
