### ISSUE TITLE
[Chrome] Notification for session expiry

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#40]
During upload of large number of files if user session has expired then a prompt should be given or user should be kept logged in till all uploads are finished.

I am trying to upload 1000 files and after a while it just stopped incrementing the number for total files. When I refreshed the page I was logged out.

**Comment by montyanderson** [comment]
Session expiry is now re-set every time you take an action. I.e. they can last infinitely long but expire after 24 hours of no usage.
