### ISSUE TITLE
[Feature Request] Select multiple files for deletion

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#41]
Ability to select multiple files for deletion or moving them between folders. 

A `Select All` checkbox at the top and an individual checkbox next to each file.

**Comment by super3** [comment]
I've modified this issue as I think #30 covers the move part. @gabedealmeida 

1. A left clicks on a file or folder which causes it to be selected
2. A delete button appears in the top of the interface
3. The user is able to select multiple files or folders by holding shift
4. The user clicks the delete button and the files are deleted after a confirm
