### ISSUE TITLE
[Chrome] Hamburger menu doesn't expand on resized Chrome 

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#42]
![image](https://user-images.githubusercontent.com/15882196/104648548-49bdce80-56d9-11eb-8b17-f66b453f243b.png)

After resizing Chrome tab the hamburger menu should populate with Blog/Forum/Logout options but it doesn't

**Comment by montyanderson** [comment]
We've removed the hamburger!
