### ISSUE TITLE
[Feature Request] Change "My Files" to Customer Name/ Organization Name

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#48]
This would be ideal to showcase Customer's name or Organization name instead of `My Files`. Added feature would be the ability to change this name with `Edit` function as shown below. This name could be accepted during signup.

![image](https://user-images.githubusercontent.com/15882196/106098390-f75fc180-615e-11eb-95ff-75ef68d52c8a.png)

**Comment by super3** [comment]
@nerdatwork This is a good idea, but since we don't collect a name and we want to keep user information at a minimum we can't add this right now. Might be something we can look at in the future.
