### ISSUE TITLE
[Feature Request] Ability to sign up to Vortex using Google/Facebook/Twitter

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#51]
It would be nice to have this feature. This helps to avoid remembering credentials. Most users are already logged in to their google/facebook/twitter so they just have to give permission.

**Comment by super3** [comment]
@nerdatwork Our intent is to merge this with the Storj/Tardigrade login. So it will use whatever login system that uses, which doesn't support login via social. Although I agree Google/Facebook/Twitter would be easier, we really want the social media companies to control login access to your secure and private storage?

**Comment by nerdatwork** [comment]
I never thought it like that which made me think of Login with Trezor.

https://wiki.trezor.io/Developers_guide:Trezor_Connect_API_-_Login_with_Trezor
