### ISSUE TITLE
[Feature Request] Protection from "Shoulder Surfing"

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#53]
S3 & Apps have credentials that could be hidden by adding ellipsis.

Access Key
`jw7u...gnrw2a`

**Comment by gabedealmeida** [comment]
Instead of the ellipsis, I took the approach of just turning all text input fields into password fields so that no one is able to shoulder surf anything. We can definitely try other approaches as well! :)

**Comment by nerdatwork** [comment]
Sounds great. Thank you 😸
