### ISSUE TITLE
File with dot on created folder

### ISSUE THREAD

**Issue by AlexandrTyshchenko** [storj-thirdparty/vortex#89]
I would like to report that after creating a new folder
![image](https://user-images.githubusercontent.com/46418015/107400974-0fdebd00-6b0b-11eb-9d39-85e96abe8e4d.png)
I see a file with a dot:
![image](https://user-images.githubusercontent.com/46418015/107401055-2d138b80-6b0b-11eb-91e6-da4978cac48f.png)

my expectation, I shouldn't see files with a dot at the beginning.

**Comment by nerdatwork** [comment]
This might help shed more light on this.
https://github.com/storj-thirdparty/vortex/issues/18

**Comment by AlexandrTyshchenko** [comment]
I completely understand how it working. My report about bad UI and user confusion with mixing two technologies (folders and objects).
As you can see on the screenshot, we have a "New Folder" button, so user expectation - will create a blank folder 
So, I pay your attention again to this issue, please thinking twice, and not mixing two technologies on UI.
