### ISSUE TITLE
Folder uploaded through duplicati returns "null" page when trying to open it in file browser

### ISSUE THREAD

**Issue by benjaminsirb** [storj-thirdparty/vortex#92]
Screenshot below:

<img width="1860" alt="Screen Shot 2021-02-09 at 5 12 06 PM" src="https://user-images.githubusercontent.com/38050125/107435366-0b5dd880-6afa-11eb-95f9-8dd7b0469358.png">

**Comment by gabedealmeida** [comment]
I haven't been able to replicate this issue.

**Comment by benjaminsirb** [comment]
Steps I take to recreate:

1. Create new account
2. Follow backup with duplicati steps for s3 compatible endpoint (https://vortex.storj.io/app/apps)
3. Run backup
4. Navigate to file browser tab in vortex (https://vortex.storj.io/app/browser)
5. (Edit to add: Clicking on the backed up directory) returns a blank page with the word "null"
