### ISSUE TITLE
Duplicati documentation enhancement

### ISSUE THREAD

**Issue by nerdatwork** [storj-thirdparty/vortex#95]
Following enhancements are suggested to make sure sections in Duplicati are properly reflected in the documentation.

<s>Create backup</s> should be `Add backup` as seen under Duplicati. ADD `Click Next` at the end of the instruction.
<mockup>

<hr>

<s>Set Passphrase</S> should be `General backup settings` as seen under Duplicati. ADD `Click Next` at the end of the instruction.
![image](https://user-images.githubusercontent.com/15882196/107497591-ca78c900-6bb8-11eb-83a1-ff66fc0b4ada.png)

![image](https://user-images.githubusercontent.com/15882196/107513973-00c14300-6bcf-11eb-864b-40238af09352.png)

<hr>

<s>Configure Backup</s> should be `Backup destination` as seen under Duplicati. "Server" should be bold in `for Server`. `S3 Compatible Endpoint` , `Bucket Name`, `Access Key`, `Secret Key` could be self linked to section with credentials so user doesn't have to scroll up and down to search. 
Alternatively a pop up could be shown with respective credentials which will remove the need to scroll. Scrolling up and then searching which section user was in the configuration step might seem tedious/confusing.

![image](https://user-images.githubusercontent.com/15882196/107514138-441bb180-6bcf-11eb-8f6b-03d42464a99c.png)

Mockup for `S3 compatible Endpoint` as hyperlink that pops up the credential
![image](https://user-images.githubusercontent.com/15882196/107495691-694ff600-6bb6-11eb-83f3-c277ec897144.png)

<hr>

<s>Select</s> **CLICK** Test Connection.
![image](https://user-images.githubusercontent.com/15882196/107496726-ad8fc600-6bb7-11eb-823a-63b6c6619c3d.png)

<hr>

Under Configure Backup, _You should see Connection Worked! If you see an error, please verify that the credentials were copied properly, or contact support for assistance._: `Contact support` should be linked to support page instead of making user search for it.  ADD `Click Next` at the end of the instruction.

<hr>

<s>Destination and Schedule</s> `Source data` as seen under Duplicati. After  `we will backup our collection of cat pictures.` ADD `Click Next` at the end of the instruction.
![image](https://user-images.githubusercontent.com/15882196/107514264-72998c80-6bcf-11eb-991a-c787b25b3892.png)

You can then set a schedule for the backups. ADD `Click Next` at the end of the instruction.

**Comment by super3** [comment]
@nerdatwork Is going to make this a pull request.
